name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use the Node.js version supported by your Next.js project
          cache: 'npm' # Cache npm dependencies to speed up the workflow

      # Step 3: Install dependencies using npm
      - name: Install Dependencies
        run: npm install

      # Step 4: Copy .env.example files to .env (if applicable)
      - name: Copy .env.example files
        shell: bash
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;

      # Step 5: Run Typecheck (if your project uses TypeScript)
      - name: Typecheck
        run: npm run typecheck # Replace with your typecheck script if different

      # Step 6: Run Linting
      - name: Lint
        run: npm run lint # Replace with your lint script if different

      # Step 7: Build the Next.js project
      - name: Build
        run: npm run build